server {
    listen      80;
    server_name Honeypot;

    return 301 https://$host$request_uri;
}





server {
    listen       443 ssl http2;
    server_name  localhost;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    #access_log  /var/log/nginx/host.access.log  main;

    server_tokens  off;

    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/main.conf;

    root /usr/share/nginx/html;
    index  index.php;

    add_header X-Frame-Options "deny"; # Prevents from being embedded in an iframe
    add_header X-Contenty-Type-Options nosniff; # Prevents the browser from interpreting files as a different MIME type than specified.
    add_header Strict-Transport-Security 'max-age=172800; includeSubDomains';

    location / {
	limit_except GET POST { deny all; }
        try_files $uri $uri/ =404;
    }


    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }    
}

